///
/// Export styles for the types of BOM's generated by this program
/// Author: Justin Morrow
///

namespace JPMorrow.Excel 
{
    // a place for various
    public class ExcelSheetStyle 
    {
        
        public string SheetTitleSuffix { get; private set; }
        public string[] ColumnHeaders { get; private set; }
        public char[] ColumnExtents { get; private set; }
        
        public ExcelSheetStyle(string sheet_title_suffix, string[] headers, char[] extents) 
        {
            ColumnHeaders = headers;
            ColumnExtents = extents;
            SheetTitleSuffix = sheet_title_suffix;
        }
    }

    public static class ExportStyle 
    {
        public static ExcelSheetStyle WirePull = new ExcelSheetStyle(
            " - PPB - M.P.A.C.T.",
            new[] { "Wire Pull #", "Panel", "Circuits", "Wire Size", "Wire Color", "Length", "Wire Material", "Conduit Diameter" },
            new[] { 'A', 'H' }
        );

        public static ExcelSheetStyle WireTotal = new ExcelSheetStyle(
            " - WPT - M.P.A.C.T.",
            new[] { "Wire Size", "Wire Color", "Length Totals" },
            new[] { 'A', 'C' }
        );

        public static ExcelSheetStyle Labor = new ExcelSheetStyle(
            " - LB - M.P.A.C.T.",
            new[] { "Type", "Qty", "Labor Per Unit", "Labor Code", "Total Labor Hours" },
            new[] { 'A', 'E' }
        );

        public static ExcelSheetStyle ElecRoom = new ExcelSheetStyle(
            " - ERB - M.P.A.C.T. - ",
            new[] { "Part Name", "Qty", "Labor Per Unit", "Labor Unit", "Total Labor Hours" },
            new[] { 'A', 'E' }
        );

        public static ExcelSheetStyle ConduitAndWireOnly = new ExcelSheetStyle(
            " - Conduit And Wire Only - M.P.A.C.T. - ",
            new[] { "From", "To", "Length", "Wire Size", "Diameter", "Set(s)", "Conduit Type" },
            new[] { 'A', 'G' }
        );

        public static ExcelSheetStyle ConduitOnly = new ExcelSheetStyle(
            " - Conduit Only - M.P.A.C.T. - ",
            new[] { "Length", "Diameter", "Conduit Type" },
            new[] { 'A', 'C' }
        );

        public static ExcelSheetStyle LegacyP3InWall = new ExcelSheetStyle(
            " - P3 In Wall - M.P.A.C.T. - ",
            new[] { "Part Name", "Qty", "Labor Per Unit", "Labor Code", "Total Labor Hours" },
            new[] { 'A', 'E' }
        );
    }
}
